### ISSUE TITLE
Fine tune Triggers auto populated in prompt when a fine tune is selected

### ISSUE THREAD

**Issue by ianccwip** [replicate/reflux#2]
This would be really useful as currently have to navigate to the model page on Replicate to dig out the trigger...

**Comment by Pwntus** [comment]
I've added this list here so that you can see which trigger word goes to which model, it's not perfect though since there's no defined place where we can get the trigger word from.

<img width="565" alt="Screenshot 2024-08-23 at 18 57 50" src="https://github.com/user-attachments/assets/1cc20617-4dca-47de-af9e-eda5d9c37ea6">
